apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: ENVIRONMENT_VAR_1
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: key1
        - name: ENVIRONMENT_VAR_2
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: key2

